export default {
  small: {
    subTitle: { fontSize: 20 },
    icon: 25,
    iconMargin: 10,
    displayIcon: 60,
    tabHeight: 70,
    tabLabel: 15,
    tabHeading: 20,
    tabMarginBottom: 7,
    tabMarginTop: 7,
    displayTitle: { fontSize: 20, lineHeight: 25 },
    title: { fontSize: 22 },
    container: { padding: 20 },
    text: { fontSize: 15, lineHeight: 21 },
    quote: { fontSize: 17, lineHeight: 23 }
  },
  medium: {
    subTitle: { fontSize: 27 },
    icon: 35,
    iconMargin: 15,
    displayIcon: 90,
    tabHeight: 90,
    tabLabel: 17,
    tabHeading: 25,
    tabMarginBottom: 7,
    tabMarginTop: 15,
    displayTitle: { fontSize: 33, lineHeight: 40 },
    title: { fontSize: 30 },
    container: { padding: 30 },
    text: { fontSize: 22, lineHeight: 33 },
    quote: { fontSize: 25, lineHeight: 35 }
  },
  large: {
    subTitle: { fontSize: 30 },
    icon: 40,
    iconMargin: 20,
    displayIcon: 130,
    tabHeight: 100,
    tabLabel: 20,
    tabHeading: 30,
    tabMarginBottom: 0,
    tabMarginTop: 0,
    displayTitle: { fontSize: 50, lineHeight: 65 },
    title: { fontSize: 40 },
    container: { padding: 35 },
    text: { fontSize: 25, lineHeight: 35 },
    quote: { fontSize: 30, lineHeight: 40 }
  }
};
