export default {
  small: {
    container: { padding: 20 },
    controls: { height: 30 },
    displayIcon: 60,
    displayTitle: { fontSize: 20, lineHeight: 25 },
    icon: 25,
    iconMargin: 10,
    logo: { width: 180 },
    quote: { fontSize: 19, lineHeight: 26 },
    subTitle: { fontSize: 20 },
    tabHeading: 20,
    bottomTabHeight: 70,
    topTabHeight: 80,
    tabLabel: 12,
    tabMarginBottom: 9,
    tabMarginTop: 9,
    text: { fontSize: 17, lineHeight: 24 },
    title: { fontSize: 22 }
  },
  medium: {
    container: { padding: 30 },
    controls: { height: 35 },
    displayIcon: 90,
    displayTitle: { fontSize: 33, lineHeight: 40, paddingVertical: 10 },
    icon: 35,
    iconMargin: 15,
    logo: { width: 270 },
    quote: { fontSize: 27, lineHeight: 36, paddingBottom: 10 },
    subTitle: { fontSize: 27 },
    tabHeading: 25,
    bottomTabHeight: 90,
    topTabHeight: 90,
    tabLabel: 17,
    tabMarginBottom: 7,
    tabMarginTop: 15,
    text: { fontSize: 24, lineHeight: 34 },
    title: { fontSize: 30 }
  },
  large: {
    container: { padding: 35 },
    controls: { height: 40 },
    displayIcon: 130,
    displayTitle: { fontSize: 50, lineHeight: 65, paddingVertical: 20 },
    icon: 40,
    iconMargin: 20,
    logo: { width: 300 },
    quote: { fontSize: 30, lineHeight: 40, paddingBottom: 20 },
    subTitle: { fontSize: 30 },
    tabHeading: 30,
    bottomTabHeight: 100,
    topTabHeight: 100,
    tabLabel: 20,
    tabMarginBottom: 0,
    tabMarginTop: 0,
    text: { fontSize: 25, lineHeight: 35 },
    title: { fontSize: 40 }
  }
};
