export default {
  small: {
    bottomTabHeight: 70,
    button: { paddingVertical: 20 },
    container: { padding: 20 },
    controls: { height: 30, marginBottom: 20 },
    days: { gap: 20 },
    displayIcon: 60,
    displayTitle: { fontSize: 20, lineHeight: 25 },
    icon: 25,
    iconMargin: 10,
    logo: { width: 180 },
    months: { gap: 20 },
    monthItem: { paddingVertical: 20 },
    quote: { fontSize: 20, lineHeight: 26 },
    subTitle: { fontSize: 20 },
    tabHeading: 20,
    tabLabel: 12,
    tabMarginBottom: 9,
    tabMarginTop: 9,
    text: { fontSize: 17, lineHeight: 24 },
    title: { fontSize: 22 },
    topTabHeight: 80
  },
  medium: {
    bottomTabHeight: 100,
    button: { paddingVertical: 20 },
    container: { padding: 30 },
    controls: { height: 35, marginBottom: 40 },
    days: { gap: 35 },
    displayIcon: 90,
    displayTitle: { fontSize: 33, lineHeight: 40, paddingVertical: 10 },
    icon: 35,
    iconMargin: 15,
    logo: { width: 270 },
    months: { gap: 30 },
    monthItem: { paddingVertical: 30 },
    quote: { fontSize: 30, lineHeight: 40, paddingBottom: 10 },
    subTitle: { fontSize: 30 },
    tabHeading: 25,
    tabLabel: 17,
    tabMarginBottom: 12,
    tabMarginTop: 15,
    text: { fontSize: 27, lineHeight: 39 },
    title: { fontSize: 30 },
    topTabHeight: 100
  },
  large: {
    bottomTabHeight: 100,
    button: { paddingVertical: 20 },
    container: { padding: 35 },
    controls: { height: 60, marginBottom: 40, marginTop: 10 },
    days: { gap: 45 },
    displayIcon: 130,
    displayTitle: { fontSize: 50, lineHeight: 65, paddingVertical: 20 },
    icon: 40,
    iconMargin: 20,
    logo: { width: 300 },
    months: { gap: 40 },
    monthItem: { paddingVertical: 40 },
    quote: { fontSize: 33, lineHeight: 43, paddingBottom: 20 },
    subTitle: { fontSize: 30 },
    tabHeading: 30,
    tabLabel: 20,
    tabMarginBottom: 0,
    tabMarginTop: 0,
    text: { fontSize: 27, lineHeight: 39 },
    title: { fontSize: 40 },
    topTabHeight: 100
  }
};
