name: Build test lint
run-name: Build test lint | ${{ github.actor }} | ${{ github.ref_name }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Build project
        run: expo export:web

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test
