name: Build and test project

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Build project
        env:
          RUN_NAME: ${{ github.workflow }} - ${{ github.head_ref }}
        run: expo export:web
          echo "::set-env name=RUN_NAME::${RUN_NAME}"

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test
