name: CI
run-name: ${{ github.actor }} CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: |
        npm install -g expo-cli
        npm install

    - name: Build project
      run: expo build:web

    - name: Test project
      run: npm run test
