name: Build and test project
run-name: ${{ github.actor }} build and test project ${{ github.repository }}

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        npm install -g expo-cli
        npm install

    - name: Build project
      run: expo export:web

    - name: Test project
      run: npm run test
