name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  setup_directory:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ADMIN_USERNAME }}"

      - name: Install dependencies
        run: |
          npm install -g npm-check-updates

      - name: Check for updates
        run: |
          ncu -u

      - name: Check working directory
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::set-output name=directory_status::true"
            echo "Files ready to commit, run the next job."
          else
            echo "::set-output name=directory_status::false"
            echo "Working directory clean, exit the job."
          fi

  bump-versions:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup_directory.outputs.directory_status == 'true'

    steps:
      - run: |
          echo Bump versions

  skip-version-bump:
    needs: bump-versions
    runs-on: ubuntu-latest
    if: needs.setup_directory.outputs.directory_status == 'false'

    steps:
      - run: |
          echo Skip version bump
