name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  check-for-new-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ADMIN_USERNAME }}"

      - name: Install dependencies
        run: |
          npm install -g npm-check-updates

      - name: Check for updates
        run: |
          ncu -u

  bump-versions:
    runs-on: ubuntu-latest
    if: "! $(git status --porcelain)"
    steps:
      - run: |
          echo Bumping versions

  close-job:
    runs-on: ubuntu-latest
    if: "$(git status --porcelain)"
    steps:
      - run: |
          echo Skipping version bump
