name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ADMIN_USERNAME }}"

      - name: Install dependencies
        run: |
          npm install -g npm-check-updates

      - name: Check for updates
        run: |
          ncu -u

      - name: Check working directory
        id: check_status
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "STATUS=unclean" >> $GITHUB_ENV
          else
            echo "STATUS=clean" >> $GITHUB_ENV
          fi

      - name: Print STATUS variable
        run: |
          echo "STATUS: ${{ env.STATUS }}"

  bump-versions:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.check_status == 'unclean'

    steps:
      - run: |
          echo Bump versions

  close-job:
    needs: setup
    runs-on: ubuntu-latest
    if: needs.setup.outputs.check_status == 'clean'

    steps:
      - run: |
          echo Skipping version bump
