name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        id: set-output-step
        run: echo "::set-output name=my_output::Hello, world!"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "The value of my_output is ${{ needs.job1.outputs.my_output }}"
