name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  check_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Check working directory
        id: status
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "The working directory is not clean. Skipping the second job."
            exit 78  # Exit with a neutral exit code (78) to indicate a skipped job
          else
            echo "The working directory is clean. Proceeding to the second job."
          fi

  second_job:
    needs: check_directory
    runs-on: ubuntu-latest
    steps:
      - name: Run the second job
        run: |
          echo "This is the second job."
          # Perform the necessary actions for the second job
