name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  bump-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ADMIN_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ADMIN_USERNAME }}"

      - name: Install dependencies
        run: |
          npm install -g npm-check-updates
          npm install

      - name: Update packages
        run: |
          ncu -u
          npm install --force
          git commit -m "Auotomated version control" package.json

      - name: Push updates
        run: git push origin ${{ github.ref_name }}

      - name: Install jq
        run: sudo apt-get -y install jq

      - name: Dependabot rebase
        run: |
          PULLS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&head=dependabot")

          for PULL in $(echo "${PULLS}" | jq -r '.[].number'); do
            curl -s -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/${PULL}/update-branch" \
              -d '{"expected_head_sha": null}'
          done
