name: Bump versions
run-name: Bump versions | ${{ github.actor }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    branch:
      default: "develop"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "##[set-env name=MY_VARIABLE]Hello, world!"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "The value of MY_VARIABLE is ${{ env.MY_VARIABLE }}"
