name: Create release
run-name: Create release | ${{ github.actor }} | ${{ github.ref_name }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && (startsWith(github.head_ref, 'release/major') || startsWith(github.head_ref, 'release/minor') || startsWith(github.head_ref, 'release/patch'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        run: |
          echo "::set-output name=version::$(cat package.json| grep 'version'| awk '{print $2}'| tr -d \",)"
        id: version

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: JustForToday ${{ steps.version.outputs.version }}
          body: |
            Built from ${{ github.sha }}
          draft: false
          prerelease: false

  close-job:
    runs-on: ubuntu-latest
    name: Skipping release creation
    if: github.event.pull_request.merged == false || (!startsWith(github.head_ref, 'release/major') || !startsWith(github.head_ref, 'release/minor') || !startsWith(github.head_ref, 'release/patch'))
    steps:
      - run: |
          echo Skipping release creation
