name: EAS build iOS
run-name: EAS build iOS | ${{ github.run_id }} | ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      branch:
        default: "develop"
        description: "EAS: [ develop | staging | production ]"
        type: string
        required: true

jobs:
  eas-build-ios:
    runs-on: macos-latest

    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret"
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Build iOS app
        run: eas build --platform ios --local --non-interactive --output ${{ github.workspace }}/app-release.ipa

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ github.workspace }}/app-release.ipa
