name: EAS build
run-name: EAS build | ${{ github.run_id }} | ${{ github.ref_name }}

on:
  push:
    branches:
      - main

jobs:
  eas-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Create production build
        run: eas build -e staging -p android --non-interactive
