name: EAS develop preview

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - feature/*

  jobs:
    eas-develop-preview:
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write

      steps:
        - name: Check for EXPO_TOKEN
          run: |
            if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
              echo "You must provide an EXPO_TOKEN secretrepo's secrets
              exit 1
            fi

        - name: Checkout code
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Use Node.js 16
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: npm

        - name: Setup EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}

        - name: Install dependencies
          run: |
          npm install -g expo-cli
          npm install

        - name: Create preview
          uses: expo/expo-github-action/preview@v8
          with:
            command: eas update --branch develop
