name: Create label
run-name: Create label | ${{ github.actor }} | ${{ github.ref_name }}

on: [pull_request_target]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Create label
        uses: actions/labeler@v4
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
