name: Prepare release
run-name: Prepare release | ${{ github.actor }} | ${{ github.ref_name }}

on:
  create:
    branches:
      - release/*

jobs:
  prepare-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
      - name: Apply version bump (major)
        if: startsWith(github.head_ref, 'release/major'
        run: npm version major
      - name: Apply version bump (minor)
        if: startsWith(github.head_ref, 'release/minor'
        run: npm version minor
      - name: Apply version bump (patch)
        if: startsWith(github.head_ref, 'release/patch'
        run: npm version patch
      - name: Git push version bump
        run: git push origin ${{ github.ref_name }} --force
      - id: set-version
        name: Output version change
        run: npm pkg get version
