name: Test release
run-name: Test release | ${{ github.run_id }} | branch - ${{ github.head_ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Build project
        run: expo export:web

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test
