name: Test release
run-name: Test release | ${{ github.actor }} | ${{ github.head_ref }}

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  test-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install -g expo-cli
          npm install

      - name: Build project
        run: expo export:web

      - name: Lint project
        run: npm run lint

      - name: Test project
        run: npm run test
